name: mitzone
description: "Mitzone transforms real-world encounters into meaningful digital connections."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  go_router: ^17.4.0
  image_picker: ^1.2.3
  path: ^1.9.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.17.1
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/mitzone_app_icon.png
