create table if not exists public.connection_requests (id uuid primary key default gen_random_uuid(), sender_user_id uuid not null references auth.users(id), recipient_user_id uuid not null references auth.users(id), encounter_id uuid not null references public.encounters(id), context_id text, status text not null default 'pending' check(status in ('pending','accepted','declined')), created_at timestamptz not null default now(), responded_at timestamptz, check(sender_user_id <> recipient_user_id));
create table if not exists public.connections (id uuid primary key default gen_random_uuid(), user_a_id uuid not null references auth.users(id), user_b_id uuid not null references auth.users(id), encounter_id uuid not null references public.encounters(id), context_id text, connected_at timestamptz not null default now(), unique(user_a_id,user_b_id), check(user_a_id < user_b_id));
alter table public.connection_requests enable row level security; alter table public.connections enable row level security;
create policy "participants read requests" on public.connection_requests for select to authenticated using(auth.uid()=sender_user_id or auth.uid()=recipient_user_id);
create policy "participants read connections" on public.connections for select to authenticated using(auth.uid()=user_a_id or auth.uid()=user_b_id);
revoke insert,update,delete on public.connection_requests from authenticated; revoke insert,update,delete on public.connections from authenticated;
create index if not exists connection_requests_recipient_status_idx on public.connection_requests(recipient_user_id,status);

create or replace function public.send_connection_request(p_other_user_id uuid, p_encounter_id uuid) returns public.connection_requests language plpgsql security definer set search_path=public as $$
declare existing public.connection_requests; result public.connection_requests;
begin
 if auth.uid() is null or auth.uid()=p_other_user_id then raise exception 'unauthorized'; end if;
 if not exists(select 1 from encounters e where e.id=p_encounter_id and ((e.user_a=auth.uid() and e.user_b=p_other_user_id) or (e.user_b=auth.uid() and e.user_a=p_other_user_id))) then raise exception 'encounter unavailable'; end if;
 if exists(select 1 from blocks b where (b.blocker_user_id=auth.uid() and b.blocked_user_id=p_other_user_id) or (b.blocker_user_id=p_other_user_id and b.blocked_user_id=auth.uid())) then raise exception 'blocked'; end if;
 select * into existing from connection_requests where status='pending' and ((sender_user_id=auth.uid() and recipient_user_id=p_other_user_id) or (sender_user_id=p_other_user_id and recipient_user_id=auth.uid())) limit 1;
 if existing.id is not null then return existing; end if;
 insert into connection_requests(sender_user_id,recipient_user_id,encounter_id) values(auth.uid(),p_other_user_id,p_encounter_id) returning * into result; return result;
end; $$;
create or replace function public.accept_connection_request(p_request_id uuid) returns public.connection_requests language plpgsql security definer set search_path=public as $$ declare r public.connection_requests; begin select * into r from connection_requests where id=p_request_id and recipient_user_id=auth.uid() and status='pending' for update; if not found then raise exception 'request unavailable'; end if; if exists(select 1 from blocks b where (b.blocker_user_id=r.sender_user_id and b.blocked_user_id=r.recipient_user_id) or (b.blocker_user_id=r.recipient_user_id and b.blocked_user_id=r.sender_user_id)) then raise exception 'blocked'; end if; update connection_requests set status='accepted',responded_at=now() where id=r.id returning * into r; insert into connections(user_a_id,user_b_id,encounter_id,context_id) values(least(r.sender_user_id,r.recipient_user_id),greatest(r.sender_user_id,r.recipient_user_id),r.encounter_id,r.context_id) on conflict(user_a_id,user_b_id) do nothing; return r; end; $$;
create or replace function public.decline_connection_request(p_request_id uuid) returns public.connection_requests language plpgsql security definer set search_path=public as $$ declare r public.connection_requests; begin update connection_requests set status='declined',responded_at=now() where id=p_request_id and recipient_user_id=auth.uid() and status='pending' returning * into r; if not found then raise exception 'request unavailable'; end if; return r; end; $$;
revoke all on function public.send_connection_request(uuid,uuid), public.accept_connection_request(uuid), public.decline_connection_request(uuid) from public; grant execute on function public.send_connection_request(uuid,uuid), public.accept_connection_request(uuid), public.decline_connection_request(uuid) to authenticated;
