create unique index if not exists notifications_social_event_unique on public.notifications(recipient_user_id,type,entity_id) where type in ('connectionRequest','connectionAccepted');
drop policy if exists "participants read connections" on public.connections;
create policy "eligible participants read connections" on public.connections for select to authenticated using((auth.uid()=user_a_id or auth.uid()=user_b_id) and not exists(select 1 from public.blocks b where (b.blocker_user_id=user_a_id and b.blocked_user_id=user_b_id) or (b.blocker_user_id=user_b_id and b.blocked_user_id=user_a_id)));
create or replace function public.send_connection_request(p_other_user_id uuid,p_encounter_id uuid) returns public.connection_requests language plpgsql security definer set search_path=public as $$
declare old public.connection_requests; result public.connection_requests;
begin
 if auth.uid() is null or auth.uid()=p_other_user_id then raise exception 'unauthorized'; end if;
 if not exists(select 1 from encounters e where e.id=p_encounter_id and e.overlap_end>=now() and ((e.user_a=auth.uid() and e.user_b=p_other_user_id) or (e.user_b=auth.uid() and e.user_a=p_other_user_id))) then raise exception 'encounter unavailable'; end if;
 if exists(select 1 from blocks b where (b.blocker_user_id=auth.uid() and b.blocked_user_id=p_other_user_id) or (b.blocker_user_id=p_other_user_id and b.blocked_user_id=auth.uid())) then raise exception 'blocked'; end if;
 select * into old from connection_requests where status='pending' and ((sender_user_id=auth.uid() and recipient_user_id=p_other_user_id) or (sender_user_id=p_other_user_id and recipient_user_id=auth.uid())) order by created_at limit 1 for update;
 if old.id is not null then
   if old.sender_user_id=p_other_user_id then update connection_requests set status='accepted',responded_at=now() where id=old.id returning * into result; insert into connections(user_a_id,user_b_id,encounter_id,context_id) values(least(auth.uid(),p_other_user_id),greatest(auth.uid(),p_other_user_id),old.encounter_id,old.context_id) on conflict(user_a_id,user_b_id) do nothing; insert into notifications(recipient_user_id,type,actor_user_id,entity_id,destination) values(old.sender_user_id,'connectionAccepted',auth.uid(),old.id::text,'/app/matches') on conflict do nothing; return result; end if;
   return old;
 end if;
 insert into connection_requests(sender_user_id,recipient_user_id,encounter_id) values(auth.uid(),p_other_user_id,p_encounter_id) returning * into result;
 insert into notifications(recipient_user_id,type,actor_user_id,entity_id,destination) values(p_other_user_id,'connectionRequest',auth.uid(),result.id::text,'/app/matches') on conflict do nothing; return result;
end; $$;
create or replace function public.accept_connection_request(p_request_id uuid) returns public.connection_requests language plpgsql security definer set search_path=public as $$ declare r public.connection_requests; begin select cr.* into r from connection_requests cr join encounters e on e.id=cr.encounter_id where cr.id=p_request_id and cr.recipient_user_id=auth.uid() and cr.status='pending' and e.overlap_end>=now() and not exists(select 1 from blocks b where (b.blocker_user_id=cr.sender_user_id and b.blocked_user_id=cr.recipient_user_id) or (b.blocker_user_id=cr.recipient_user_id and b.blocked_user_id=cr.sender_user_id)) for update; if not found then raise exception 'request unavailable'; end if; update connection_requests set status='accepted',responded_at=now() where id=r.id returning * into r; insert into connections(user_a_id,user_b_id,encounter_id,context_id) values(least(r.sender_user_id,r.recipient_user_id),greatest(r.sender_user_id,r.recipient_user_id),r.encounter_id,r.context_id) on conflict(user_a_id,user_b_id) do nothing; insert into notifications(recipient_user_id,type,actor_user_id,entity_id,destination) values(r.sender_user_id,'connectionAccepted',auth.uid(),r.id::text,'/app/matches') on conflict do nothing; return r; end; $$;
create or replace function public.remove_connection(p_connection_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin delete from connections where id=p_connection_id and (user_a_id=auth.uid() or user_b_id=auth.uid()); end; $$;
revoke all on function public.remove_connection(uuid) from public; grant execute on function public.remove_connection(uuid) to authenticated;
